/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Seminar1;

import java.awt.Font;
import javax.swing.UIManager;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    
    public static final Font FONT = new Font("Lucida Sans", Font.PLAIN, 15);

    public static void main(String[] args) {
        com.formdev.flatlaf.FlatLightLaf.setup(); // setup FlatLaf Light theme to be used by MainFrame
        UIManager.put("OptionPane.messageFont", FONT); // set JOptionPane message font
        UIManager.put("OptionPane.buttonFont", FONT); // set JOptionPane button font
        MainFrame.main(args);
    }
}
