/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Seminar1;

import javax.swing.BorderFactory;
import javax.swing.JToggleButton;

/**
 *
 * @author Luka
 */

public class PassengerSeat extends javax.swing.JPanel {
    
//    private PassengerInfo psgInfo;
    private int passengerNumber;
    private String passengerName;
    private String passengerSurname;
    private String selectedSeat = "";
    private JToggleButton selectedSeatButton; // to make it easier to unselect later, that's the only purpose
    
    public static int PANEL_HEIGHT = 59; // the height of this panel
    public static int BOTTOM_BORDER = 15; // the size of the bottom border
    
    /*
    NOTE: the container panel that is a part of this object serves 1 purpose:
    to (for some reason) have the PassengerSeat objects added to seatPanelPsg
    centered, just like I want. To align them to the left, remove the container
    panel, but also be sure to change the mouse pressed mouse listener for
    this object/the radio button!
    */
    
    /**
     * Creates new form PassengerSeat
     * @param psgNumber
     * @param psgName
     * @param psgSurname
     */
    public PassengerSeat(int psgNumber, String psgName, String psgSurname){  //boolean vis) {
        initComponents();
        this.setName(String.valueOf(psgNumber)); //String.valueOf(pd.getPassengerNumber()));
//        this.psgInfo = pd;
        this.setBorder(BorderFactory.createEmptyBorder(0, 0, BOTTOM_BORDER, 0));

        this.passengerNumber = psgNumber;
        this.passengerName = psgName;
        this.passengerSurname = psgSurname;
        
//        String nameSurname = pd.getPsgName() + " " + pd.getSurname();
        String nameSurname = psgName + " " + psgSurname;
        this.labelNameSurname.setText(nameSurname);
        
        this.addMouseListener(new MousePressedPassengerSeat());
        this.radioIsChoosing.addMouseListener(new MousePressedPassengerSeat());
    }
    
    
    public int getPassengerNumber(){
//        return this.psgInfo.getPassengerNumber();
        return this.passengerNumber;
    }
    
    public boolean getSelecting(){
        /*
        Return whether the radio button, which indicates if this passenger
        is choosing/selecting his seat, is selected.
        */
        return this.radioIsChoosing.isSelected();
    }
    
    public void setSelecting(boolean val){
        if (val){
            this.radioIsChoosing.doClick();
        }
        else{
            this.bg.clearSelection();
        }
    }
    
    public void setPassenger(int psgNumber, String psgName, String psgSurname){ //PassengerDetails pd){
//        this.psgInfo = pd;
        this.passengerNumber = psgNumber;
        this.passengerName = psgName;
        this.passengerSurname = psgSurname;
        String nameSurname = psgName + " " + psgSurname;
        this.labelNameSurname.setText(nameSurname);
    }
    
    public String getPsgName(){
//        return this.psgInfo.getPsgName();
        return this.passengerName;
    }
    
    public String getSurname(){
//        return this.psgInfo.getSurname();
        return this.passengerSurname;
    }
    
    public void setSeat(String seat){
        this.selectedSeat = seat;
    }
    
    public String getSeat(){
        return this.selectedSeat;
    }
    
    public void setButtonSeat(JToggleButton b){
        this.selectedSeatButton = b;
    }
    
    public JToggleButton getButtonSeat(){
        return this.selectedSeatButton;
    }
    
    public void setLabelSeatText(String text){
        this.labelSeat.setText(text);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        labelNameSurname = new javax.swing.JLabel();
        labelSeat = new javax.swing.JLabel();
        radioIsChoosing = new javax.swing.JRadioButton();

        setToolTipText("Click on this passenger's name, or the button to the right, to enable selecting a seat for this passenger.");

        labelNameSurname.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        labelNameSurname.setText("Name Surname");

        labelSeat.setFont(new java.awt.Font("Lucida Sans", 0, 15)); // NOI18N
        labelSeat.setText("Seat: (none)");

        bg.add(radioIsChoosing);
        radioIsChoosing.setName("isChoosing"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSeat)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNameSurname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioIsChoosing)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelNameSurname)
                    .addComponent(radioIsChoosing))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSeat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg;
    private javax.swing.JLabel labelNameSurname;
    private javax.swing.JLabel labelSeat;
    private javax.swing.JRadioButton radioIsChoosing;
    // End of variables declaration//GEN-END:variables
}
